### ISSUE TITLE
Support for IFC 4

### ISSUE THREAD

**Issue by fehnomenal** [agviegas/IFC.js#16]
Hi, I would like to use your lib but we need to work with IFC 4 files. What would it take to support IFC 4?

**Comment by agviegas** [comment]
Hi @fehnomenal! We are still working in IFC2x3. Once we have that up and running, implementing IFC4 will be easy, mainly because parsing (reading) the properties is easy, while generating the geometry is hard. As far as I know, the vast majority of geometric entities in IFC4 are defined in a similar way to IFC2x3, so adding the additional properties / modifications in the ifc classes of the parser should make this work with most IFC4 files. 

Stay tuned for future updates and let us know if you want to contribute with this, as this is something easy to implement.

**Comment by fehnomenal** [comment]
Thank you for answering. Out of curiosity I tested an IFC4 model and it loaded without problems. I guess the geometry in this case is backwards compatible :sweat_smile:

**Comment by agviegas** [comment]
Great! Even though we will eventually support  any IFC file, you can contribute to the project sharing some of the files that you are trying to load and are not working, so we can implement the missing entities as soon as possible. 🙂

**Comment by berlotti** [comment]
4.3 will have quite some changes on the alignment curve.... that might have an impact. If you want you can join the IFC 4.3 implementors go at it together with other vendors.

**Comment by agviegas** [comment]
Hi @berlotti! Lately we've been migrating everything to WASM (see [this repository](https://github.com/tomvandig/web-ifc)), and we're still a long way from being able to support the current state of IFC, so right now I don't know if we're going to be able to contribute much to that group. However, we would love to be part of it!

**Comment by berlotti** [comment]
Participants are being monitored for contributions and active engagement.... maybe next time then :-)

**Comment by agviegas** [comment]
Hey @fehnomenal we already support IFC4, so maybe you can give a try to the current implementation. There are entities missing, but we are on it. Feel free to open new issues about this in [web-ifc](https://github.com/tomvandig/web-ifc). As this is the library in charge of the parsing now, I'm closing this issue.
