### ISSUE TITLE
"Uncaught TypeError: can't assign to property "_HasType" on 19145: not an object" when loading an IFC file

### ISSUE THREAD

**Issue by vinnividivicci** [agviegas/IFC.js#21]
![image](https://user-images.githubusercontent.com/591242/102638607-c767dc00-4125-11eb-9cdb-2564d059e330.png)

The element 19145 in question is:
#19145= IFCFLOWSEGMENT('0qwzB5jvb6bfAMNnWR5Sze',#41,'Round Duct:Taps:1755002',$,'Round Duct:Taps',#19122,#19142,'1755002');

The IFC file in question is in IFC 2x3 schema.

Thanks for your work on this!

**Comment by agviegas** [comment]
Hey! We are not able to load all IFC projects yet, as we don't support all geometries / classes. In your screenshot, the array of names of the first line are the ifc classes that have not been implemented yet. 

You can send me me the files you want to load to integrate their classes in the code as soon as possible. Otherwise, stay tuned for upcoming updates!

**Comment by vinnividivicci** [comment]
Unfortunately, I am not able to share that specific file. However it seems
to be mostly mechanical or HVAC classes that are causing the problem.

I will keep my eye open for further updates!

Thanks for this great initiative!
