### ISSUE TITLE
BoundingBox: TypeError: geometryMap[type] is not a function

### ISSUE THREAD

**Issue by Moult** [agviegas/IFC.js#22]
Btw, awesome project! The OSArch community has written a news article about your project! https://osarch.org/2020/12/21/a-new-browser-ifc-viewer-is-released-in-ifc-js/

I see this error in the console when I try to load a small file (the file doesn't load):

geometry-map.js:23 Error with item IfcWallStandardCase of type BoundingBox: TypeError: geometryMap[type] is not a function

I can email you the file for private debugging?

![2020-12-22-134711_783x298_scrot](https://user-images.githubusercontent.com/88302/102842926-3e6ddf00-445c-11eb-9069-0d78be3adac3.png)

There's a bunch of other errors which may or may not be related:

![2020-12-22-134853_458x546_scrot](https://user-images.githubusercontent.com/88302/102843017-707f4100-445c-11eb-978b-ce4867a00158.png)
![2020-12-22-134843_638x543_scrot](https://user-images.githubusercontent.com/88302/102843018-71b06e00-445c-11eb-867a-a8e73de4c52b.png)

**Comment by agviegas** [comment]
Hi @Moult, and thanks! The article is awesome! 🙂 The problem here is that geometries of type _BoundingBox_ have not been implemented yet. Yes, send me the file so I can implement them. We are close to have all types of geometries implemented, and having more IFC files to test is of great help.

**Comment by Moult** [comment]
@agviegas which email can I send to?

**Comment by agviegas** [comment]
antoniogviegas@hotmail.com

**Comment by Moult** [comment]
Sent

**Comment by Moult** [comment]
BTW @agviegas feel free to join the rest of the OSArch community (and many devs from multiple free software projects like Blender, IfcOpenShell, and FreeCAD) in the ##architect channel on Freenode IRC (or use Matrix if you're up for something more modern!)

**Comment by agviegas** [comment]
Great, I have joined both chats! 🙂

**Comment by agviegas** [comment]
Hey,  I took some days off for christmas. Now I am back to this and I plan to have this solved throughout the following days. 🙂
 
![image](https://user-images.githubusercontent.com/56475338/103465079-bed3f000-4d38-11eb-8bab-5927bdce7c73.png)
![image](https://user-images.githubusercontent.com/56475338/103465083-d27f5680-4d38-11eb-8505-ee5b59d07a8f.png)

**Comment by agviegas** [comment]
Hey, sorry, these days were busier than expected. We have implemented a bunch of geometric entities that were missing (circular hollow profiles, composite profiles with trimmed curves, etc). We are close to solve all the issues with this file. Stay tuned!

![image](https://user-images.githubusercontent.com/56475338/104507892-b5c00a00-55e7-11eb-9582-7441f838426d.png)
![image](https://user-images.githubusercontent.com/56475338/104507914-beb0db80-55e7-11eb-8560-4ac42e1bdd8f.png)
![image](https://user-images.githubusercontent.com/56475338/104507963-d0927e80-55e7-11eb-8ff0-4b82afa30d63.png)

**Comment by Moult** [comment]
Don't worry I have hundreds of files I'll be pushing through this... :D

**Comment by agviegas** [comment]
With the last [deployed changes](https://agviegas.github.io/IFC.js/examples/00/) this file should load correctly. There are several things to take into account:
- I am not implementing IfcAnnotations for now because I am closing other geometry types. Nonetheless, if you have a file with several IfcAnnotation instances, we can maybe implement that as a separate issue.
- There are extra edges in one of the wardroves. My guess is that this has been created using simetry (?). Nevertheless, edges is something I am not paying to much attention for now, so I think that this is something assumable at the current state of the library.
- I have implemented a very rudimentary selection system that allows you to see object properties in the console.

Looking forward to hearing what you think and trying more of your files. 😉 Geometry types only need to be implemented the first time, so this should go much faster in future issues.
